// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djuaphbzoitjqjtlxmxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqdWFwaGJ6b2l0anFqdGx4bXhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMjM4ODUsImV4cCI6MjA2OTc5OTg4NX0.h-owDFfnfENfLNq8mt8gpl5Eq0iJq0HdxDg4-QgUzoI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});